###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = /home/rio/Tools/yazi
$menu = rofi -show drun
$wlogout = wlogout
$browser = /home/rio/Tools/firefox/firefox
$visual_studio_code = /home/rio/Tools/VSCode-linux-x64/bin/code
